# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logininfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, unique=True)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
